version: '3.8'
services:
  frontend:
    image: nengoilahoang/self-note:latest
    container_name: seft_note_frontend
    restart: always
    ports:
      - "8080:80" # Máy thật mở cổng 80 trỏ vào cổng 80 bên trong container
    environment:
      - VITE_API_URL=${VITE_API_URL}